export const accounts = [
    {
      id: 1,
      name: "Pablo",
      surname: "Jackson",
      age: "34",
      country: "USA",
      password: "pablo",
      balance: 10000,
    },
    {
      id: 2,
      name: "Kate",
      surname: "Madison",
      age: "29",
      country: "Spain",
      password: "kate",
      balance: 4500,
    },
    {
      id: 3,
      name: "Mark",
      surname: "Davison",
      age: "30",
      country: "Canada",
      password: "mark",
      balance: 5200,
    },
    {
      id: 4,
      name: "Jane",
      surname: "Mur",
      age: "37",
      country: "France",
      password: "jane",
      balance: 2500,
    },
  ]